"""
Biznes Kategoriyalar va Reja Nomlari
=====================================
480 ta biznes reja — 24 ta yo'nalish — 4 ta asosiy faoliyat turi
Har bir faoliyat turi uchun maxsus xarajat strukturasi.
"""

# ══════════════════════════════════════════════════════════
#  4 TA ASOSIY FAOLIYAT TURI VA XARAJAT STRUKTURALARI
# ══════════════════════════════════════════════════════════

FAOLIYAT_TURLARI = {
    "ishlab_chiqarish": {
        "nomi": "Ishlab chiqarish",
        "icon": "🏭",
        "tavsif": "Mahsulot ishlab chiqarish, zavod va sexlar",
        "xomashyo_ulushi": 0.475,
        "ish_haqi_ulushi": 0.15,
        "energiya_ulushi": 0.075,
        "amortizatsiya_ulushi": 0.075,
        "soliq_ulushi": 0.04,
        "marketing_ulushi": 0.035,
        "boshqa_ulushi": 0.04,
        "transport_ulushi": 0.0,
        "ijara_ulushi": 0.0,
        "amortizatsiya_stavka": 0.15,
        "amortizatsiya_majburiy": True,
        "rentabellik_min": 0.15,
        "rentabellik_max": 0.30,
        "asosiy_xarajat": "xomashyo",
        "asosiy_xarajat_nomi": "Xomashyo va materiallar",
        "mahsulot_label": "Ishlab chiqariladigan mahsulot nomi",
        "hajm_label": "Yillik ishlab chiqarish hajmi",
        "narx_label": "Bitta mahsulotning sotish narxi",
        "qoshimcha_fieldlar": [
            {"name": "xomashyo_narx", "label": "Bitta mahsulot uchun xomashyo narxi", "suffix": "so'm", "placeholder": "Masalan: 50000"},
            {"name": "uskuna_qiymati", "label": "Uskunalar umumiy qiymati", "suffix": "so'm", "placeholder": "Masalan: 100000000"},
            {"name": "energiya_oylik", "label": "Oylik energiya xarajati", "suffix": "so'm", "placeholder": "Masalan: 5000000"},
        ],
    },
    "qishloq_xojaligi": {
        "nomi": "Qishloq xo'jaligi",
        "icon": "🌾",
        "tavsif": "Dehqonchilik, chorvachilik, fermerlik",
        "xomashyo_ulushi": 0.40,
        "ish_haqi_ulushi": 0.125,
        "energiya_ulushi": 0.075,
        "amortizatsiya_ulushi": 0.075,
        "soliq_ulushi": 0.04,
        "marketing_ulushi": 0.0,
        "boshqa_ulushi": 0.04,
        "transport_ulushi": 0.075,
        "ijara_ulushi": 0.0,
        "amortizatsiya_stavka": 0.10,
        "amortizatsiya_majburiy": False,
        "rentabellik_min": 0.20,
        "rentabellik_max": 0.40,
        "asosiy_xarajat": "urug_yem",
        "asosiy_xarajat_nomi": "Urug', yem va o'g'it",
        "mahsulot_label": "Yetishtiriladigan mahsulot / hayvon turi",
        "hajm_label": "Yillik hosil / mahsulot hajmi",
        "narx_label": "Bitta birlik sotish narxi",
        "qoshimcha_fieldlar": [
            {"name": "urug_yem_narx", "label": "Urug'/yem/o'g'it uchun yillik xarajat", "suffix": "so'm", "placeholder": "Masalan: 30000000"},
            {"name": "texnika_xarajat", "label": "Texnika xizmatlari (yillik)", "suffix": "so'm", "placeholder": "Masalan: 15000000"},
            {"name": "yer_ijarasi", "label": "Yer ijarasi (yillik)", "suffix": "so'm", "placeholder": "Masalan: 10000000"},
        ],
    },
    "savdo": {
        "nomi": "Savdo bizneslari",
        "icon": "🏪",
        "tavsif": "Do'kon, supermarket, chakana va ulgurji savdo",
        "xomashyo_ulushi": 0.775,
        "ish_haqi_ulushi": 0.075,
        "energiya_ulushi": 0.0,
        "amortizatsiya_ulushi": 0.04,
        "soliq_ulushi": 0.03,
        "marketing_ulushi": 0.02,
        "boshqa_ulushi": 0.0,
        "transport_ulushi": 0.035,
        "ijara_ulushi": 0.05,
        "amortizatsiya_stavka": 0.04,
        "amortizatsiya_majburiy": False,
        "rentabellik_min": 0.10,
        "rentabellik_max": 0.20,
        "asosiy_xarajat": "tovar",
        "asosiy_xarajat_nomi": "Tovar xaridi",
        "mahsulot_label": "Sotiladigan tovar turi",
        "hajm_label": "Yillik sotish hajmi",
        "narx_label": "Bitta tovarning o'rtacha sotish narxi",
        "qoshimcha_fieldlar": [
            {"name": "tovar_xaridi", "label": "Bitta tovarning xarid narxi", "suffix": "so'm", "placeholder": "Masalan: 80000"},
            {"name": "dokon_ijarasi", "label": "Do'kon ijarasi (oylik)", "suffix": "so'm", "placeholder": "Masalan: 5000000"},
            {"name": "transport_xarajat", "label": "Transport xarajati (oylik)", "suffix": "so'm", "placeholder": "Masalan: 3000000"},
        ],
    },
    "xizmat": {
        "nomi": "Xizmat ko'rsatish",
        "icon": "🍽",
        "tavsif": "Servis, ta'mirlash, restoran, salon, IT",
        "xomashyo_ulushi": 0.075,
        "ish_haqi_ulushi": 0.425,
        "energiya_ulushi": 0.075,
        "amortizatsiya_ulushi": 0.075,
        "soliq_ulushi": 0.04,
        "marketing_ulushi": 0.075,
        "boshqa_ulushi": 0.0,
        "transport_ulushi": 0.0,
        "ijara_ulushi": 0.15,
        "amortizatsiya_stavka": 0.075,
        "amortizatsiya_majburiy": False,
        "rentabellik_min": 0.30,
        "rentabellik_max": 0.50,
        "asosiy_xarajat": "ish_haqi",
        "asosiy_xarajat_nomi": "Ish haqi va xodimlar",
        "mahsulot_label": "Xizmat turi",
        "hajm_label": "Yillik xizmat ko'rsatish soni",
        "narx_label": "Bitta xizmatning narxi",
        "qoshimcha_fieldlar": [
            {"name": "uskuna_ijarasi", "label": "Uskunalar qiymati / ijarasi", "suffix": "so'm", "placeholder": "Masalan: 20000000"},
            {"name": "joy_ijarasi", "label": "Joy ijarasi (oylik)", "suffix": "so'm", "placeholder": "Masalan: 8000000"},
            {"name": "kommunal_oylik", "label": "Kommunal to'lovlar (oylik)", "suffix": "so'm", "placeholder": "Masalan: 3000000"},
        ],
    },
}


# ══════════════════════════════════════════════════════════
#  24 TA KATEGORIYA VA 480 TA REJA NOMI
# ══════════════════════════════════════════════════════════

KATEGORIYALAR = {
    # ─── 🏭 1. Ishlab chiqarish (Manufacturing) — 20 ta ───
    "ishlab_chiqarish_manufacturing": {
        "nomi": "🏭 Ishlab chiqarish (Manufacturing)",
        "faoliyat_turi": "ishlab_chiqarish",
        "rejalar": [
            "Mebel ishlab chiqarish",
            "Plastik mahsulotlar ishlab chiqarish",
            "Metall buyumlar ishlab chiqarish",
            "Alyumin eshik va romlar ishlab chiqarish",
            "Gipsokarton ishlab chiqarish",
            "Beton blok ishlab chiqarish",
            "Plastik deraza ishlab chiqarish",
            "Temir eshik ishlab chiqarish",
            "Tom yopish materiallari ishlab chiqarish",
            "Polietilen paket ishlab chiqarish",
            "Qurilish armatura ishlab chiqarish",
            "Shifer ishlab chiqarish",
            "G'isht ishlab chiqarish",
            "Keramika mahsulotlari ishlab chiqarish",
            "Plastik idish ishlab chiqarish",
            "Kabel ishlab chiqarish",
            "Yog'och buyumlar ishlab chiqarish",
            "Matras ishlab chiqarish",
            "Oshxona jihozlari ishlab chiqarish",
            "Oyna ishlab chiqarish",
        ],
    },
    # ─── 🍞 2. Oziq-ovqat ishlab chiqarish — 20 ta ───
    "oziq_ovqat": {
        "nomi": "🍞 Oziq-ovqat ishlab chiqarish",
        "faoliyat_turi": "ishlab_chiqarish",
        "rejalar": [
            "Non ishlab chiqarish",
            "Qandolat mahsulotlari ishlab chiqarish",
            "Milliy shirinliklar ishlab chiqarish",
            "Sut mahsulotlari ishlab chiqarish",
            "Kolbasa ishlab chiqarish",
            "Muzqaymoq ishlab chiqarish",
            "Mineral suv ishlab chiqarish",
            "Sharbat ishlab chiqarish",
            "Chips ishlab chiqarish",
            "Makaron ishlab chiqarish",
            "Un ishlab chiqarish",
            "Yog' ishlab chiqarish",
            "Konserva ishlab chiqarish",
            "Murabbo ishlab chiqarish",
            "Quruq meva ishlab chiqarish",
            "Asal mahsulotlari ishlab chiqarish",
            "Tuzlangan mahsulotlar ishlab chiqarish",
            "Fast food mahsulotlari ishlab chiqarish",
            "Pitsa ishlab chiqarish",
            "Lavash ishlab chiqarish",
        ],
    },
    # ─── 🌾 3. Qishloq xo'jaligi — 20 ta ───
    "qishloq_xojaligi_main": {
        "nomi": "🌾 Qishloq xo'jaligi",
        "faoliyat_turi": "qishloq_xojaligi",
        "rejalar": [
            "Issiqxona sabzavot yetishtirish",
            "Parranda fermasi",
            "Baliqchilik xo'jaligi",
            "Asalarichilik",
            "Qoramol boqish",
            "Qo'y boqish",
            "Echki boqish",
            "Quyonchilik",
            "Bedana boqish",
            "Meva bog'i tashkil etish",
            "Uzum yetishtirish",
            "Kartoshka yetishtirish",
            "Pomidor yetishtirish",
            "Bodring yetishtirish",
            "Poliz ekinlari yetishtirish",
            "Gul yetishtirish",
            "Ko'chat yetishtirish",
            "Chorva yem ishlab chiqarish",
            "Parranda yem ishlab chiqarish",
            "Baliq yem ishlab chiqarish",
        ],
    },
    # ─── 🏪 4. Savdo bizneslari — 20 ta ───
    "savdo_bizneslari": {
        "nomi": "🏪 Savdo bizneslari",
        "faoliyat_turi": "savdo",
        "rejalar": [
            "Oziq-ovqat do'koni",
            "Qurilish materiallari do'koni",
            "Mebel do'koni",
            "Elektr texnika do'koni",
            "Maishiy texnika do'koni",
            "Avto ehtiyot qismlar do'koni",
            "Telefon va aksessuarlar do'koni",
            "Kiyim do'koni",
            "Bolalar kiyimlari do'koni",
            "Poyabzal do'koni",
            "Kosmetika do'koni",
            "Sport anjomlari do'koni",
            "Kitob do'koni",
            "O'yinchoqlar do'koni",
            "Gul do'koni",
            "Parfyumeriya do'koni",
            "Ofis jihozlari do'koni",
            "Avto moylar do'koni",
            "Kompyuter texnika do'koni",
            "Zargarlik buyumlari do'koni",
        ],
    },
    # ─── 🍽 5. Xizmat ko'rsatish — 20 ta ───
    "xizmat_korsatish": {
        "nomi": "🍽 Xizmat ko'rsatish",
        "faoliyat_turi": "xizmat",
        "rejalar": [
            "Restoran",
            "Kafe",
            "Fast food",
            "Oshxona",
            "Catering xizmati",
            "Mehmonxona",
            "Hostel",
            "Avtomobil yuvish",
            "Avtoservis",
            "Shina montaj",
            "Go'zallik saloni",
            "Sartaroshxona",
            "SPA markazi",
            "Massaj saloni",
            "Fitnes markazi",
            "Bolalar o'yin markazi",
            "O'quv markazi",
            "Kompyuter o'quv markazi",
            "Til o'quv markazi",
            "Dizayn studiya",
        ],
    },
    # ─── 🧠 6. Zamonaviy bizneslar — 20 ta ───
    "zamonaviy_biznes": {
        "nomi": "🧠 Zamonaviy bizneslar",
        "faoliyat_turi": "xizmat",
        "rejalar": [
            "IT xizmatlari",
            "Web studio",
            "Mobil ilova ishlab chiqish",
            "Digital marketing agentligi",
            "SMM agentligi",
            "Grafik dizayn studio",
            "Video production",
            "Foto studio",
            "Online savdo (E-commerce)",
            "Dropshipping biznes",
            "Call center",
            "Buxgalteriya outsourcing",
            "Konsalting kompaniya",
            "Reklama agentligi",
            "Print studio",
            "3D print xizmatlari",
            "Drone xizmatlari",
            "Kuryer xizmati",
            "Logistika kompaniyasi",
            "AI xizmatlari",
        ],
    },
    # ─── 🏗 7. Qurilish va remont — 20 ta ───
    "qurilish_remont": {
        "nomi": "🏗 Qurilish va remont bizneslari",
        "faoliyat_turi": "xizmat",
        "rejalar": [
            "Qurilish kompaniyasi",
            "Remont xizmatlari",
            "Tom yopish ishlari",
            "Beton quyish xizmatlari",
            "Kafel va plitka yotqizish",
            "Elektr montaj xizmatlari",
            "Santexnika xizmatlari",
            "Gipsokarton ishlari",
            "Fasad bezak ishlari",
            "Alyumin konstruksiya montaj",
            "Deraza o'rnatish xizmatlari",
            "Eshik o'rnatish xizmatlari",
            "Parket o'rnatish",
            "Pol qoplamalari ishlari",
            "Bo'yoq ishlari",
            "Qurilish texnika ijarasi",
            "Mini ekskavator xizmatlari",
            "Beton nasos xizmatlari",
            "Arxitektura xizmatlari",
            "Dizayn xizmatlari",
        ],
    },
    # ─── 🚚 8. Transport va logistika — 20 ta ───
    "transport_logistika": {
        "nomi": "🚚 Transport va logistika",
        "faoliyat_turi": "xizmat",
        "rejalar": [
            "Yuk tashish xizmati",
            "Taksi xizmati",
            "Mikroavtobus yo'lovchi tashish",
            "Avto ijarasi",
            "Maxsus texnika ijarasi",
            "Logistika markazi",
            "Ombor xizmatlari",
            "Sovutkich ombori",
            "Kuryer xizmati",
            "Pochta xizmati",
            "Xalqaro yuk tashish",
            "Shahar ichida yuk tashish",
            "Avtobus transport xizmati",
            "Avtomobil diagnostika markazi",
            "Avtomobil tuning markazi",
            "Avto evakuator xizmati",
            "Avtomobil bo'yash",
            "Avto salon",
            "Avto detailing",
            "Avto signalizatsiya o'rnatish",
        ],
    },
    # ─── 🧵 9. Yengil sanoat — 20 ta ───
    "yengil_sanoat": {
        "nomi": "🧵 Yengil sanoat",
        "faoliyat_turi": "ishlab_chiqarish",
        "rejalar": [
            "Tikuvchilik sexi",
            "Trikotaj mahsulotlari ishlab chiqarish",
            "Forma tikish",
            "Sport kiyimlari ishlab chiqarish",
            "Bolalar kiyimlari ishlab chiqarish",
            "Pardalar tikish",
            "Gilam ishlab chiqarish",
            "Sun'iy charm mahsulotlari ishlab chiqarish",
            "Sumka ishlab chiqarish",
            "Poyabzal ishlab chiqarish",
            "Teridan buyumlar ishlab chiqarish",
            "Yostiq ishlab chiqarish",
            "Ko'rpa ishlab chiqarish",
            "Pardozlash matolari ishlab chiqarish",
            "Sochiq ishlab chiqarish",
            "Paypoq ishlab chiqarish",
            "Ish kiyimlari ishlab chiqarish",
            "Tekstil bo'yash",
            "Tekstil chop etish",
            "Tekstil dizayn studiyasi",
        ],
    },
    # ─── 🏥 10. Tibbiyot va sog'liq — 20 ta ───
    "tibbiyot_sogliq": {
        "nomi": "🏥 Tibbiyot va sog'liq",
        "faoliyat_turi": "xizmat",
        "rejalar": [
            "Xususiy klinika",
            "Stomatologiya klinikasi",
            "Diagnostika markazi",
            "Laboratoriya",
            "Farmatsiya do'koni",
            "Optika do'koni",
            "Reabilitatsiya markazi",
            "Fizioterapiya markazi",
            "Sport tibbiyoti markazi",
            "Bolalar tibbiyot markazi",
            "Tibbiy kosmetologiya",
            "Psixologiya markazi",
            "Tibbiy massaj markazi",
            "Uyga tibbiy xizmat",
            "Hemodializ markazi",
            "Sanitariya xizmatlari",
            "Dezinfeksiya xizmatlari",
            "Veterinariya klinikasi",
            "Hayvonlar dorixonasi",
            "Uy hayvonlari parvarish markazi",
        ],
    },
    # ─── 🎓 11. Ta'lim va trening — 20 ta ───
    "talim_trening": {
        "nomi": "🎓 Ta'lim va trening",
        "faoliyat_turi": "xizmat",
        "rejalar": [
            "Maktabgacha ta'lim markazi",
            "Xususiy maktab",
            "Til o'quv markazi",
            "IT o'quv markazi",
            "Robototexnika o'quv markazi",
            "Buxgalteriya kurslari",
            "Marketing kurslari",
            "Dizayn kurslari",
            "Tikuvchilik kurslari",
            "SMM kurslari",
            "Dasturlash kurslari",
            "Online ta'lim platformasi",
            "Repetitorlik markazi",
            "IELTS tayyorlov markazi",
            "Matematika markazi",
            "Fizika markazi",
            "Abituriyent tayyorlov markazi",
            "Biznes trening markazi",
            "Soft skill kurslari",
            "Kasb-hunar markazi",
        ],
    },
    # ─── 🎉 12. Turizm va ko'ngilochar — 20 ta ───
    "turizm_kongilochar": {
        "nomi": "🎉 Turizm va ko'ngilochar",
        "faoliyat_turi": "xizmat",
        "rejalar": [
            "Turizm agentligi",
            "Sayohat kompaniyasi",
            "Mehmonxona",
            "Hostel",
            "Dam olish maskani",
            "Bolalar o'yin markazi",
            "Karaoke klub",
            "Bilyard klub",
            "Bowling markazi",
            "Kinoteatr",
            "VR o'yin markazi",
            "Escape room",
            "Attraksion park",
            "Akvapark",
            "Sport maydonlari ijarasi",
            "Futbol maydoni ijarasi",
            "Tennis korti ijarasi",
            "Velosiped ijarasi",
            "Turistik gid xizmatlari",
            "Ekoturizm biznesi",
        ],
    },
    # ─── 🧼 13. Maishiy xizmatlar — 20 ta ───
    "maishiy_xizmatlar": {
        "nomi": "🧼 Maishiy xizmatlar",
        "faoliyat_turi": "xizmat",
        "rejalar": [
            "Kir yuvish xizmati (Laundry)",
            "Kimyoviy tozalash (Dry cleaning)",
            "Uy tozalash xizmati",
            "Ofis tozalash xizmati",
            "Gilam tozalash xizmati",
            "Mebel tozalash xizmati",
            "Deraza yuvish xizmati",
            "Dezinfeksiya xizmati",
            "Hasharotlarga qarshi xizmat",
            "Uy ta'mirlash xizmati",
            "Bog' parvarishi xizmati",
            "Landshaft dizayni",
            "Qor tozalash xizmati",
            "Maishiy texnika ta'miri",
            "Sovutgich ta'miri",
            "Konditsioner ta'miri",
            "Televizor ta'miri",
            "Kompyuter ta'miri",
            "Telefon ta'miri",
            "Printer ta'miri",
        ],
    },
    # ─── 📦 14. Ombor va distribyutsiya — 20 ta ───
    "ombor_distribyutsiya": {
        "nomi": "📦 Ombor va distribyutsiya",
        "faoliyat_turi": "savdo",
        "rejalar": [
            "Distribyutorlik kompaniyasi",
            "Oziq-ovqat distribyutsiyasi",
            "Ichimliklar distribyutsiyasi",
            "Farmatsevtika distribyutsiyasi",
            "Qurilish materiallari distribyutsiyasi",
            "Sovutkich ombori",
            "Meva-sabzavot ombori",
            "Logistika markazi",
            "E-commerce ombori",
            "Fulfillment markazi",
            "Yuk qadoqlash xizmati",
            "Yuk markirovka xizmati",
            "Konteyner saqlash xizmati",
            "Yuk saralash markazi",
            "Yuk ekspeditsiya xizmati",
            "Avtomobil ehtiyot qismlar ombori",
            "Texnika ombori",
            "Qurilish texnika ombori",
            "Import eksport ombori",
            "Bojxona ombori",
        ],
    },
    # ─── 🌱 15. Ekologik va yashil biznes — 20 ta ───
    "ekologik_biznes": {
        "nomi": "🌱 Ekologik va yashil biznes",
        "faoliyat_turi": "ishlab_chiqarish",
        "rejalar": [
            "Quyosh paneli o'rnatish",
            "Quyosh elektr stansiyasi",
            "Shamol energiya tizimi",
            "Bio o'g'it ishlab chiqarish",
            "Organik mahsulotlar yetishtirish",
            "Organik oziq-ovqat do'koni",
            "Chiqindilarni qayta ishlash",
            "Plastik qayta ishlash",
            "Metall qayta ishlash",
            "Qog'oz qayta ishlash",
            "Shisha qayta ishlash",
            "Kompost ishlab chiqarish",
            "Ekologik tozalash xizmatlari",
            "Ekologik qadoqlash ishlab chiqarish",
            "Bambuk mahsulotlari ishlab chiqarish",
            "Bio gaz ishlab chiqarish",
            "Suv filtrlash tizimlari",
            "Yomg'ir suvini yig'ish tizimi",
            "Ekologik qurilish materiallari",
            "Ekologik turizm",
        ],
    },
    # ─── 🐾 16. Hayvonlar bilan bog'liq — 20 ta ───
    "hayvonlar_biznes": {
        "nomi": "🐾 Hayvonlar bilan bog'liq biznes",
        "faoliyat_turi": "qishloq_xojaligi",
        "rejalar": [
            "Uy hayvonlari do'koni",
            "Veterinariya klinikasi",
            "Hayvonlar mehmonxonasi",
            "Hayvonlar parvarishi xizmati",
            "Itlarni o'qitish markazi",
            "Itlar uchun oziq-ovqat ishlab chiqarish",
            "Mushuklar uchun oziq-ovqat ishlab chiqarish",
            "Uy hayvonlari kiyimlari ishlab chiqarish",
            "Akvarium baliqlari savdosi",
            "Baliq yetishtirish xo'jaligi",
            "Dekorativ baliq fermasi",
            "Ot fermasi",
            "Ot minish markazi",
            "Tuya fermasi",
            "Chorva fermasi",
            "Sut fermasi",
            "Parranda fermasi",
            "Bedana fermasi",
            "Kurka fermasi",
            "Tovuq tuxumi ishlab chiqarish",
        ],
    },
    # ─── 🎨 17. Kreativ va media — 20 ta ───
    "kreativ_media": {
        "nomi": "🎨 Kreativ va media biznes",
        "faoliyat_turi": "xizmat",
        "rejalar": [
            "Foto studio",
            "Video production studio",
            "Reklama agentligi",
            "Grafik dizayn studio",
            "Animatsiya studio",
            "Podcast studio",
            "Musiqa yozish studio",
            "Kino ishlab chiqarish",
            "Reklama rolik ishlab chiqarish",
            "Brend dizayn studio",
            "Kontent yaratish agentligi",
            "YouTube studio",
            "Influencer marketing agentligi",
            "Event dizayn studio",
            "Dekor studio",
            "To'y dekoratsiya xizmati",
            "Banner ishlab chiqarish",
            "LED reklama ishlab chiqarish",
            "Print studio",
            "3D vizualizatsiya studio",
        ],
    },
    # ─── 💻 18. Raqamli bizneslar — 20 ta ───
    "raqamli_biznes": {
        "nomi": "💻 Raqamli bizneslar",
        "faoliyat_turi": "xizmat",
        "rejalar": [
            "Web sayt ishlab chiqish",
            "Mobil ilova ishlab chiqish",
            "SaaS platforma",
            "Online marketplace",
            "Online kurs platformasi",
            "CRM tizim ishlab chiqish",
            "ERP tizim ishlab chiqish",
            "Cyber security xizmatlari",
            "Cloud xizmatlari",
            "Hosting kompaniyasi",
            "Data analiz kompaniyasi",
            "AI xizmatlari",
            "Chatbot ishlab chiqish",
            "NFT platformasi",
            "Blockchain xizmatlari",
            "Fintech platforma",
            "Online banking xizmatlari",
            "Digital marketing platforma",
            "SEO agentligi",
            "Affiliate marketing platformasi",
        ],
    },
    # ─── 🏨 19. Mehmonxona va turar joy — 20 ta ───
    "mehmonxona_turar": {
        "nomi": "🏨 Mehmonxona va turar joy bizneslari",
        "faoliyat_turi": "xizmat",
        "rejalar": [
            "Mini mehmonxona",
            "Apart hotel",
            "Guest house",
            "Hostel biznesi",
            "Dam olish uyi",
            "Turistik baza",
            "Tog' turizmi markazi",
            "Cho'l turizmi",
            "Oilaviy mehmon uyi",
            "Servis apartamenti",
            "Ijara kvartiralar biznesi",
            "Airbnb biznesi",
            "Kemping markazi",
            "Glamping biznesi",
            "Kurort dam olish maskani",
            "Sanatoriya",
            "Spa resort",
            "Ski resort",
            "Plyaj dam olish maskani",
            "Fishing resort",
        ],
    },
    # ─── 🏪 20. Savdo va retail kengaytirilgan — 20 ta ───
    "savdo_retail": {
        "nomi": "🏪 Savdo va retail kengaytirilgan",
        "faoliyat_turi": "savdo",
        "rejalar": [
            "Supermarket",
            "Mini market",
            "Elektronika supermarket",
            "Qurilish supermarket",
            "Dehqon bozori savdosi",
            "Meva sabzavot savdosi",
            "Go'sht do'koni",
            "Baliq do'koni",
            "Non do'koni",
            "Shirinliklar do'koni",
            "Qahva do'koni",
            "Choy do'koni",
            "Sovg'alar do'koni",
            "Suvenir do'koni",
            "O'yinchoqlar supermarket",
            "Sport do'koni",
            "Velosiped do'koni",
            "Qurilish asboblari do'koni",
            "Elektr jihozlari do'koni",
            "Uy jihozlari do'koni",
        ],
    },
    # ─── 🧪 21. Innovatsion ishlab chiqarish — 20 ta ───
    "innovatsion_ishlab_chiqarish": {
        "nomi": "🧪 Innovatsion ishlab chiqarish",
        "faoliyat_turi": "ishlab_chiqarish",
        "rejalar": [
            "3D printer ishlab chiqarish",
            "Robototexnika ishlab chiqarish",
            "Smart home qurilmalar ishlab chiqarish",
            "LED lampalar ishlab chiqarish",
            "Elektr skuter ishlab chiqarish",
            "Elektr velosiped ishlab chiqarish",
            "Elektr avtomobil zaryad stansiyasi",
            "IoT qurilmalar ishlab chiqarish",
            "Dron ishlab chiqarish",
            "Elektr batareya ishlab chiqarish",
            "Smart soat ishlab chiqarish",
            "VR qurilmalar ishlab chiqarish",
            "AR texnologiya ishlab chiqarish",
            "Elektr scooter ijarasi",
            "Elektr velosiped ijarasi",
            "Robot xizmatlari",
            "Smart parking tizimi",
            "Smart transport tizimi",
            "Smart qishloq xo'jaligi texnologiyalari",
            "Agro dron xizmatlari",
        ],
    },
    # ─── 🎭 22. Event va xizmat bizneslari — 20 ta ───
    "event_xizmat": {
        "nomi": "🎭 Event va xizmat bizneslari",
        "faoliyat_turi": "xizmat",
        "rejalar": [
            "To'y tashkil qilish xizmati",
            "Event agentlik",
            "Tug'ilgan kun tashkil qilish",
            "Korporativ tadbirlar tashkil qilish",
            "Konsert tashkil qilish",
            "Festival tashkil qilish",
            "Ko'rgazma tashkil qilish",
            "Fotobudka ijarasi",
            "Dekor ijarasi",
            "Sahna ijarasi",
            "Ovoz apparatlari ijarasi",
            "Yoritish texnikasi ijarasi",
            "DJ xizmatlari",
            "Animator xizmatlari",
            "Bolalar bayrami tashkil qilish",
            "Catering xizmatlari",
            "Bar xizmatlari",
            "Muzqaymoq aravachasi biznesi",
            "Street food aravachasi",
            "Food truck biznesi",
        ],
    },
    # ─── 🏭 23. Sanoat xizmatlari — 20 ta ───
    "sanoat_xizmatlari": {
        "nomi": "🏭 Sanoat xizmatlari",
        "faoliyat_turi": "ishlab_chiqarish",
        "rejalar": [
            "Metall kesish xizmatlari",
            "Lazer kesish xizmatlari",
            "CNC ishlov berish",
            "Metall payvandlash",
            "Metall bo'yash",
            "Metall qoplama xizmatlari",
            "Yog'och kesish xizmatlari",
            "Yog'och o'ymakorligi",
            "Plastik kesish xizmatlari",
            "Shisha kesish xizmatlari",
            "Qadoqlash ishlab chiqarish",
            "Etiketka ishlab chiqarish",
            "Plastik qadoqlash ishlab chiqarish",
            "Karton qadoqlash ishlab chiqarish",
            "Yog'och qadoqlash ishlab chiqarish",
            "Metall konteyner ishlab chiqarish",
            "Transport konteyner ishlab chiqarish",
            "Sovutkich konteyner ishlab chiqarish",
            "Mobil ofis ishlab chiqarish",
            "Mobil uy ishlab chiqarish",
        ],
    },
    # ─── 🌐 24. Online bizneslar — 20 ta ───
    "online_bizneslar": {
        "nomi": "🌐 Online bizneslar",
        "faoliyat_turi": "xizmat",
        "rejalar": [
            "Online marketplace",
            "Online oziq ovqat savdosi",
            "Online dorixona",
            "Online kiyim do'koni",
            "Online mebel do'koni",
            "Online elektronika savdosi",
            "Online kitob do'koni",
            "Online kurs platformasi",
            "Online repetitor platformasi",
            "Freelance platforma",
            "Onlayn dizayn xizmatlari",
            "Onlayn marketing xizmatlari",
            "Onlayn reklama platformasi",
            "Onlayn logistika platformasi",
            "Onlayn to'lov tizimi",
            "Onlayn bank xizmatlari",
            "Onlayn sug'urta xizmatlari",
            "Onlayn konsultatsiya xizmatlari",
            "Onlayn psixologiya xizmatlari",
            "Onlayn tibbiy maslahat xizmatlari",
        ],
    },
}


# ══════════════════════════════════════════════════════════
#  YORDAMCHI FUNKSIYALAR
# ══════════════════════════════════════════════════════════

def get_all_plans() -> list:
    """Barcha 480 ta reja nomini qaytaradi."""
    plans = []
    for cat_key, cat_data in KATEGORIYALAR.items():
        faoliyat = cat_data["faoliyat_turi"]
        for reja in cat_data["rejalar"]:
            plans.append({
                "nomi": reja,
                "kategoriya": cat_data["nomi"],
                "kategoriya_key": cat_key,
                "faoliyat_turi": faoliyat,
                "faoliyat_nomi": FAOLIYAT_TURLARI[faoliyat]["nomi"],
            })
    return plans


def search_plans(query: str, limit: int = 20) -> list:
    """Reja nomlarini qidirish (fuzzy)."""
    if not query or len(query) < 2:
        return []
    query_lower = query.lower().strip()
    results = []
    for plan in get_all_plans():
        if query_lower in plan["nomi"].lower():
            results.append(plan)
            if len(results) >= limit:
                break
    return results


def get_faoliyat_turi(plan_name: str) -> str:
    """Reja nomiga ko'ra faoliyat turini aniqlash."""
    for cat_key, cat_data in KATEGORIYALAR.items():
        if plan_name in cat_data["rejalar"]:
            return cat_data["faoliyat_turi"]
    return "ishlab_chiqarish"  # default


def get_cost_structure(faoliyat_turi: str) -> dict:
    """Faoliyat turiga mos xarajat strukturasi."""
    return FAOLIYAT_TURLARI.get(faoliyat_turi, FAOLIYAT_TURLARI["ishlab_chiqarish"])


def get_categories_for_frontend() -> dict:
    """Frontend uchun kategoriyalar va rejalar."""
    result = {
        "faoliyat_turlari": {},
        "kategoriyalar": {},
        "barcha_rejalar": get_all_plans(),
    }
    for key, val in FAOLIYAT_TURLARI.items():
        result["faoliyat_turlari"][key] = {
            "nomi": val["nomi"],
            "icon": val["icon"],
            "tavsif": val["tavsif"],
            "mahsulot_label": val["mahsulot_label"],
            "hajm_label": val["hajm_label"],
            "narx_label": val["narx_label"],
            "qoshimcha_fieldlar": val["qoshimcha_fieldlar"],
        }
    for cat_key, cat_data in KATEGORIYALAR.items():
        result["kategoriyalar"][cat_key] = {
            "nomi": cat_data["nomi"],
            "faoliyat_turi": cat_data["faoliyat_turi"],
            "rejalar": cat_data["rejalar"],
        }
    return result
